inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 11

training:
    task: polynomial_regression
    data: uniform
    task_kwargs: {}
    batch_size: 1
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 10000
    curriculum:
        degree:
          start: 1
          end: 11
          inc: 2
          interval: 2000
        points:
            start: 2
            end: 12
            inc: 2
            interval: 2000

out_dir: ../models/polynomial_regression

wandb:
    name: "polynomial_regression_toy"
