inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    "family": "gpt2"
    "n_positions": 81
    "n_dims": 128
    "n_embd": 128
    "n_layer": 6
    "n_head": 4

training:
    task: polynomial_regression
    data: uniform
    task_kwargs: {}
    batch_size: 1
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1
    curriculum:
        degree:
          start: 1
          end: 11
          inc: 2
          interval: 2000
        points:
            start: 2
            end: 12
            inc: 2
            interval: 2000

out_dir: ../models/polynomial_regression

wandb:
    name: "polynomial_regression_toy"
